language: objective-c
osx_image: xcode8
sudo: ture

cache:
  - bundler
  - cocoapods

before_install:
 - rvm use system
 - sudo gem install cocoapods -v '1.1.1'

script:
 - cd ./HSFontiOS
 - pod install
 - xcodebuild -list
 - xcodebuild -workspace HSFontiOS.xcworkspace -scheme HSFontiOS  build -sdk iphonesimulator
