# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSFontiOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSFontiOS
	pod 'HSFont'
    pod 'Google/Analytics'
    pod 'Google/SignIn'
    
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Flurry-iOS-SDK/FlurryAds'
end

target 'HSFontMac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSFontMac
    pod 'HSFont'

end
