# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'CCFontDemo.xcodeproj'

target 'CCFontiOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCFontiOS
    pod 'CCStat'
    pod 'CCFont', path:".."
end

target 'CCFontMac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCFontMac
    pod 'CCFont', path:".."

end
